RCPS-108 Prefect System: Make a QueryConstant class
RoCS2024/prefect-office-record-management-system pull request #40
Opened 2024-04-05 14:39 UTC by rosellemarithe

2024-04-09 14:07 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +        try (PreparedStatement stmt = c.prepareStatement(GET_ALL_CS_STATEMENT);
Clean this up. Check with others how to do the try with resource correctly

2024-04-09 14:08 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +            try (PreparedStatement stmt = c.prepareStatement(GET_CS_BY_ID_STATEMENT)) {
Clean this up. Check with others how to do the try with resource correctly

2024-04-09 14:08 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +        try ( PreparedStatement stmt = c.prepareStatement(RENDER_CS_STATEMENT);
Clean this up. Check with others how to do the try with resource correctly

2024-04-09 14:08 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/offense/impl/OffenseDaoImpl.java
> +        try (PreparedStatement stmt = c.prepareStatement(GET_OFFENSE_BY_ID_STATEMENT)) {
Clean this up. Check with others how to do the try with resource correctly

2024-04-10 12:03 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/appl/facade/prefect/communityservice/impl/CommunityServiceFacadeImpl.java
> +    CommunityServiceDao communityServiceDao = new CommunityServiceDaoImpl();
where is the access modifier for this?

2024-04-10 12:03 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +    Connection c = ConnectionHelper.getConnection();
Remove this connection here

2024-04-10 12:04 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +        @Override
why put extra tab space?

2024-04-10 12:04 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/offense/impl/OffenseDaoImpl.java
> +    Connection c = ConnectionHelper.getConnection();
remove this connection

2024-04-10 12:05 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/violation/impl/ViolationDaoImpl.java
> +    Connection c = ConnectionHelper.getConnection();
Remove this connection

2024-04-10 12:06 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +        try (Connection c = new ConnectionHelper().getConnection()){
how can you create a new instance of a final class?

2024-04-10 12:06 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/communityservice/impl/CommunityServiceDaoImpl.java
> +        try (Connection c = new ConnectionHelper().getConnection()){
how can you create a new instance of a final/static class?

2024-04-10 12:06 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/offense/impl/OffenseDaoImpl.java
> +        try (Connection c = new ConnectionHelper().getConnection()){
how can you create a new instance of a final/static class?

2024-04-10 12:06 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/offense/impl/OffenseDaoImpl.java
> +        try (Connection c = new ConnectionHelper().getConnection()){
how can you create a new instance of a final/static class?

2024-04-10 12:07 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/offense/impl/OffenseDaoImpl.java
> +        try (Connection c = new ConnectionHelper().getConnection()){
how can you create a new instance of a final/static class?

2024-04-10 12:07 UTC, RoCS2024 commented on src/main/java/com/prefect/office/record/management/data/dao/prefect/violation/impl/ViolationDaoImpl.java
> +        try (Connection c = new ConnectionHelper().getConnection()){
how can you create a new instance of a final/static class?

2024-04-10 12:07 UTC, RoCS2024 requested changes
see ALL comments

2024-04-11 22:56 UTC, RoCS2024 requested changes
Revert to QueryConstant class change only., We will just create a separate ticket for the rest.

2024-04-12 17:17 UTC, rosellemarithe commented
sir I created a new branch and will close this nalang po

2024-04-12 17:17 UTC, closed without merging