RCPS:132 Prefect System: Fix Offense Backend
RoCS2024/prefect-office-record-management-system pull request #51
Opened 2024-04-10 17:32 UTC by zhairanicolepacheco

&&
RCPS: 129 Prefect System: Fix CommunityServiceDaoImpl renderCs

2024-04-11 22:52 UTC, RoCS2024 requested changes
do not checkout iml files

2024-04-15 11:54 UTC, RoCS2024 commented
Build is failiing

2024-04-18 00:09 UTC, esdi-00 approved these changes
all good

2024-04-18 00:39 UTC, RoCS2024 approved these changes

2024-04-18 01:20 UTC, merged